config/routes.rb
Rails.application.routes.draw do
  root 'chatrooms#index'
  devise_for :users

  resources :messages
  resources :chatrooms, param: :id do
    resources :memberships
  end

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index]
      resources :chatrooms
      resources :messages
    end
  end

  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  belongs_to :owner, class_name: 'User'

  has_many :memberships, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :users, through: :memberships

  def owner_name
    User.find_by_id(self.owner_id).username
  end

  def member_names
    memberships = Membership.where(chatroom_id: self.id)
    names = []

    memberships.each do |membership|
      names << membership.username
    end

    names
  end
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :user
  belongs_to :chatroom

  validates_uniqueness_of :user_id, { scope: :chatroom_id, message: 'is already a member' }

  def username
    User.find_by_id(self.user_id).username
  end
end

app/models/message.rb
class Message < ApplicationRecord
  validates :body, presence: true
  
  belongs_to :user
  belongs_to :chatroom
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true

  has_many :messages
  has_many :memberships
  has_many :chatrooms, through: :memberships

  mount_uploader :profile_photo, ProfilePhotoUploader

  def admin?
    role == 'admin'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

protected

  def configure_permitted_parameters
    added_attrs = [:username, :profile_photo]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  def index
    @chatrooms = Chatroom.all
  end

  def show
    @chatroom = Chatroom.find(params[:id])
    @message = Message.new
  end

  def new
    @chatroom = Chatroom.new
  end

  def create
    @chatroom = Chatroom.new(chatroom_params)

    if @chatroom.save
      Membership.create!(user_id: current_user.id, chatroom_id: @chatroom.id)
      flash[:notice] = 'Chatroom created successfully'
      redirect_to root_path
    else
      flash.now[:notice] = @chatroom.errors.full_messages.join(' * ')
      render :new
    end
  end

  def edit
    @chatroom = Chatroom.find(params[:id])

    if current_user.id != @chatroom.owner_id
      flash[:notice] = 'You are only allowed to edit your own chatrooms.'
      redirect_to chatroom_path
    end
  end

  def update
    @chatroom = Chatroom.find(params[:id])

    if @chatroom.update_attributes(chatroom_params)
      flash[:notice] = 'Chatroom edited successfully'
      redirect_to root_path
    else
      flash.now[:notice] = @chatroom.errors.full_messages.join(' * ')
    end
  end

  def destroy
    @chatroom = Chatroom.find(params[:id])
    @chatroom.destroy
    @chatroom.memberships.destroy

    flash[:notice] = 'Chatroom deleted'
    redirect_to root_path
  end

  private

  def chatroom_params
    params.require(:chatroom).permit(:name, :owner_id)
  end
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  def new
    @users = User.all
    @chatroom = Chatroom.find(params[:chatroom_id])
    @membership = Membership.new
  end

  def create
    @users = User.all
    @chatroom = Chatroom.find(params[:chatroom_id])
    @membership = Membership.new(membership_params)
    @membership.chatroom = @chatroom

    if @membership.save
      flash[:notice] = 'User added successfully'
      redirect_to chatroom_path(@chatroom)
    else
      flash.now[:notice] = @membership.errors.full_messages.join(' * ')
      render :new
    end
  end

  def destroy
    @membership = Membership.find(params[:id])
    @membership.destroy

    flash[:notice] = 'Chatroom deleted'
    redirect_to root_path
  end

  private

  def membership_params
    params.require(:membership).permit(:user_id, :chatroom_id)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    message = Message.new(message_params)
    message.user = current_user
    if message.save
      ActionCable.server.broadcast 'messages',
        message: message.body,
        user: message.user.username
      head :ok
    end
  end

  private

  def message_params
    params.require(:message).permit(:body, :chatroom_id)
  end
end

app/views/chatrooms/edit.html.erb
<div class='left-right-margin'>
  <%- if current_user.admin? -%>
    <h2>EDIT <%= @chatroom.name.upcase %></h2>

    <%= form_for(@chatroom) do |f| %>
      <div class='field'>
        <%= f.label :name, 'Name:' %></br>
        <%= f.text_field :name %>
      </div>

      <div class='field'>
        <%= f.submit 'Edit' %>
      </div>
    <%- end -%>
  <%- else -%>
    redirect_to root_path
  <%- end -%>
<div>

app/views/chatrooms/index.html.erb
<div class='left-right-margin'>
  <%- if current_user -%>
    <h2>YOUR CHATROOMS</h2>

    <%- @chatrooms.each do |chatroom| -%>
      <%- if chatroom.member_names.include?(current_user.username) || current_user.admin? -%>
        <%= link_to chatroom.name, chatroom_path(chatroom) %></br>
      <%- end -%>
    <%- end -%><br/>

    <%= link_to 'Create chatroom', new_chatroom_path %>
  <%- else -%>
    <p>This is a pretty basic messenging application. Please sign in or sign up.</p>
  <%- end -%>
<div>

app/views/chatrooms/new.html.erb
<div class='left-right-margin'>
  <%- if current_user %>
    <h2>CREATE CHATROOM</h2>

    <%= form_for(@chatroom) do |f| %>
      <div class='field'>
        <%= f.label :name, 'Name:' %><br/>
        <%= f.text_field :name %>
      </div>

      <%= f.hidden_field :owner_id, value: current_user.id %>

      <div class='field'>
        <%= f.submit 'Create' %>
      </div>
    <%- end -%>
  <%- end -%>
</div>

app/views/chatrooms/show.html.erb
<div class='left-right-margin'>
  <%- if current_user -%>
    <h2><%= @chatroom.name.upcase %></h2>
    <h6 class='center'>Welcome, <%= current_user.username %></h6>

    <%- if @chatroom.messages.any? -%>
      <div class='black-ring' id='black-ring'>
        <%= render partial: 'messages/message', collection: @chatroom.messages.reverse %>
      </div>
    <%end%>

    <%= render partial: 'messages/message_form', locals: { message: @message, chatroom: @chatroom } %></br>

    <%- if current_user.id == @chatroom.owner_id -%>
      <%= link_to 'Invite people', new_chatroom_membership_path(@chatroom) %><br/>
      <%= link_to 'Edit this chatroom', edit_chatroom_path(@chatroom) %></br>
    <%- end -%>

    <%- if current_user.id == @chatroom.owner_id || current_user.admin? -%>
      <%= link_to 'Delete this chatroom', chatroom_path(@chatroom),
        method: :delete,
        data: { confirm: 'Are you sure?' } %>
    <%- end -%>
  <%- else -%>
    <p>This is a pretty basic messenging application. Please sign in or sign up to continue.</p>
  <%- end -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hey</title>
  <meta name='viewport' content='width=device-width, initial-scale=1.0' />
  <%= stylesheet_link_tag 'application', media: 'all' %>

    <%= javascript_include_tag 'vendor/modernizr' %>

  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
</head>
<body>

  <div class='black-underscore'>
    <div class='left-right-margin'>
      <nav class='top-bar'>
        <ul class='title-area'>
          <li class='name'>
            <h1><a href='/'>HEY</a></h1>
          </li>
        </ul>

        <section class='top-bar-section'>
          <ul class='right'>
            <%- if current_user -%>
              <li class='user-id'>Your ID: <%= current_user.id %></li>
              <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
              <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
            <%- else -%>
              <li><%= link_to 'Sign up', new_user_registration_path %></li>
              <li><%= link_to 'Sign in', new_user_session_path %></li>
            <%- end -%>
          </ul>
        </section>
      </nav>
    </div>
  </div>

  <div class='flash-messages' id='flash-messages'>
    <%- flash.each do |key, value| -%>
      <div class='flash flash-<%= key %>'>
        <%= value %>
      </div>
    <%- end -%>
  </div>

  <div>
    <%= yield %>
  </div>

  <%= javascript_include_tag 'application' %>

  <%- if Rails.env.development? || Rails.env.test? -%>
    <%= javascript_tag do %>
      window.railsEnv = '<%= Rails.env %>'
    <%- end -%>
  <%- end -%>
  <%= javascript_pack_tag 'application' %>

  <%= yield :extra_footer %>
</body>
</html>

app/views/memberships/new.html.erb
<div class='left-right-margin'>
  <%- if current_user.id == @chatroom.owner_id -%>
    <h2>INVITE PEOPLE TO <%= @chatroom.name.upcase %></h2>

    <%= form_for [@chatroom, @membership] do |f| %>
      <div class='field'>
        <%= f.label :user, 'ID of the person you want to invite:', for: 'membership_user_id' %><br/>
        <%= f.text_field :user_id %>
      </div>

      <div class='field'>
        <%= f.submit 'Invite' %>
      </div>
    <%- end -%>
  <%- end -%>
</div>

app/views/messages/_message.html.erb
<div class='chat-message'>
  <%- if message.user.profile_photo -%>
    <div class='profile-photo-container profile-photo-small'>
      <img class='profile-photo' src=<%= message.user.profile_photo %> />
    </div>
  <%- end -%>

  <strong><%= message.user.username %> </strong> (<%=message.created_at.strftime('%l:%M%p') %> on <%= message.created_at.strftime('%b %d, %G') %>):

  <%- if message.user_id == current_user.id -%>
    <span class='red-text'>
      <%= message.body %>
    </span><br/>
  <%- else -%>
    <span class='blue-text'>
      <%= message.body %>
    </span><br/>
  <%- end -%>
</div>

app/views/messages/_message_form.html.erb
</br>
<%= form_for message, remote: true, authenticity_token: true do |f| %>
  <div class='field'>
    <%= f.label :body, 'Your message:' %></br>
    <%= f.text_field :body, data: {textarea: 'message'} %>
  </div>

  <%= f.hidden_field :chatroom_id, value: chatroom.id %>

  <%= f.submit 'Send', data: {send: 'message'} %>
<% end %>